# Generated by Django 4.1.1 on 2022-09-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='almacen.categoria')),
            ],
        ),
    ]
