# Generated by Django 4.1.1 on 2022-09-22 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.categoria'),
        ),
    ]
